name: Remote Update
on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/zaustin3-subdomain.ignorelist.com/html 
            git pull origin main
            pm2 restart all  # Or your specific process name
